kind: Cluster
# apiVersion: kind.sigs.k8s.io/v1alpha3
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  disableDefaultCNI: true # disable kindnet
  podSubnet: "10.244.0.0/16"
  serviceSubnet: "10.96.0.0/12"
  # kubeProxyMode: "ipvs"
nodes:
- role: control-plane
- role: worker
- role: worker
