---
# - name: Playbook to update repo
#   hosts: web
#   become: true
#   tasks:
#   - name: Update apt repository
#     replace:
#       path: /etc/apt/sources.list
#       regexp: 'http:\/\/[^\/]*'
#       replace: 'http://mirrors.ustc.edu.cn'
#       backup: yes
#   - name: Ansible Update Cache
#     register: updatesys
#     apt:
#       name: "*"
#       update_cache: yes

# - name: Playbook to install NGINX
#   hosts: web
#   become: true
#   tasks: 
#   - name: Ansible apt install nginx
#     apt:
#       name: nginx
#       state: present
#     register: command_output
#   - debug:
#       var: command_output.stdout_lines

- name: Playbook to setup vpn
  hosts: all
  become: "yes"
  remote_user: "vagrant"

  tasks:
  - name: Install docker.io
    apt:
      name: docker.io
      state: present
  - name: Copy v2ray.service to systemd
    copy:
      src: v2ray.service
      dest: /etc/systemd/system/v2ray.service
      owner: vagrant
      group: vagrant
  - name: Restart v2ray.service
    systemd:
      state: restarted
      daemon_reload: yes
      name: v2ray
  - name: Copy proxy to /usr/local/bin/
    copy:
      src: proxy
      dest: /usr/local/bin/proxy
      mode: 0755
