Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/impish64"
    config.ssh.insert_key = false
    config.ssh.forward_x11 = true
    config.vbguest.auto_update = false
  
    config.vm.provider "virtualbox" do |vb|
      vb.cpus = 2
      vb.memory = 2048
      vb.check_guest_additions = false
    end

    config.vm.define "vm1" do |srv|
      srv.vm.hostname = "vm1"
      srv.vm.network :private_network, ip: "192.168.56.3"
    end
  
  end