ENV['VAGRANT_DEFAULT_PROVIDER']="libvirt"

Vagrant.configure("2") do |config|
    # config.vm.box = "ubuntu/impish64"
    config.vm.box = "generic/ubuntu2010"

    $init_script = <<__EOF__
    sudo apt-get update
    sudo apt-get install -qq vim net-tools openvswitch-switch
__EOF__

    config.vm.provider :libvirt do |v|
      v.memory = 1024
      v.video_type = "virtio"
      v.management_network_name = "default"
      v.management_network_address = "192.168.100.0/24"
    end

    config.vm.define "vm1" do |srv|
      srv.vm.hostname = "vm1"
      srv.vm.network :private_network, :type => "dhcp"
      srv.vm.provision "shell", inline: $init_script
    end
  end
